#!/bin/bash

install(){
  
  if [ ! ${EUID:-$(id -u)} -eq 0 ] 
  then
    echo 'You must be root to run this script'
    exit 1
  fi

  installdir=/usr/share/pywal-discord
  themesdir=$HOME/.config/pywal-discord

  unameOut="$(uname -s)"
  case "${unameOut}" in
      Darwin*)
          installdir=$HOME/.config/pywal-discord
          themesdir=$HOME/.config/pywal-discord-themes
          ;;
  esac

  mkdir -p "$themesdir"

  if [ -e "$installdir" ]
  then
	  rm -rf "$installdir"
  fi

  mkdir "$installdir"
  cp ./config/* "$installdir"
  if [ "${unameOut}" == "Darwin" ]
  then
	  cp ./pywal-discord /usr/local/bin
  else
	  cp ./pywal-discord /usr/bin/
  fi  
}

uninstall(){
  if [ ! ${EUID:-$(id -u)} -eq 0 ] 
  then
    echo 'You must be root to run this script'
    exit 1
  fi
  rm -rf $themesdir
  rm -rf $installdir
  rm /usr/local/bin/pywal-discord >/dev/null 2>&1
  rm /usr/bin/pywal-discord >/dev/null 2>&1
}

help()
{
  echo -e "Usage: "
  echo -e "install                Install script"
  echo -e "uninstall              Uninstall script"
  echo -e "help                   Show options for script"
}

value=$1

if [[ $value -ne "help" && $value -ne "install" && $value -ne "uninstall" ]]; then
  echo -e "Select valid option"
  help
else
  case "$value" in
    install) 
      install
    ;;
    uninstall) 
      uninstall
    ;;
    help) 
      help
    ;;
  esac
fi
